@startuml チケット料金
interface 顧客区分仕様
class 上映開始日時
enum 顧客区分
enum 証明書

顧客 *-- 顧客年齢
note top of 顧客年齢 : "3歳以上"
顧客 *-- "*" 証明書
顧客 "*" o-- "1..*" 顧客区分
顧客区分 .. 顧客区分仕様 : < 満たしている
顧客区分仕様 <|-- シネティズン会員仕様
シネティズン会員仕様 <|-- シネティズン会員シニア仕様
顧客区分仕様 <|-- 一般区分仕様
顧客区分仕様 <|-- シニア区分仕様
顧客区分仕様 <|-- 大学生区分仕様
顧客区分仕様 <|-- 専門学生区分仕様
顧客区分仕様 <|-- 高校生区分仕様
顧客区分仕様 <|-- 中学生区分仕様
顧客区分仕様 <|-- 小人区分仕様
note top of 小人区分仕様 : "12歳以下"
顧客区分仕様 <|-- 障がい者区分仕様
料金ポリシー <|-- 平日料金ポリシー
料金ポリシー <|-- 休日料金ポリシー
料金ポリシー <|-- レイト料金ポリシー
料金ポリシー <|-- 映画の日料金ポリシー

料金計算サービス - 顧客
料金計算サービス - 上映開始日時
料金計算サービス - 料金ポリシー : > 選択する
チケット料金 - 料金計算サービス : < 算出する
@enduml
