@startuml チケット料金
package 顧客 {
  object 個人
  object 証明書
  object 年齢
  object 顧客区分仕様
  object 顧客区分

  個人 *-- 年齢
  note top of 年齢 : "3歳以上"
  個人 *-- "*" 証明書
  個人 "*" o-- "1..*" 顧客区分
  顧客区分 <.. 顧客区分仕様 : < 満たしている
}

package 上映 {
  object 開始時間
  object 上映時間区分
  object 上映時間区分仕様

  開始時間 "*" o-- "1*" 上映時間区分
  上映時間区分 <.. 上映時間区分仕様 : < 満たしている
}

package 購入 {
  object 料金
  object 料金計算 {
    calculate(個人, 開始時間): 料金
  }
  object 基本料金ポリシー
  note bottom: 顧客区分と上映時間区分の組み合わせ

  料金 <.. 料金計算: < 算出
  料金計算 -- 基本料金ポリシー
  料金計算 -- 個人
  料金計算 -- 開始時間
}
@enduml
